### ISSUE TITLE
All Troops are Freezing

### ISSUE THREAD

**Issue by RFuller25** [bjucps209/spring22-team1#10]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "model.Game.deleteTroop(model.Troop)" because "this.game" is null
        at model.Troop.update(Troop.java:78)
        at model.Game.update(Game.java:184)
        at model.Game.lambda$11(Game.java:534)

**Comment by RFuller25** [comment]
fixed by adding game to the troop constructor.
