### ISSUE TITLE
Null location

### ISSUE THREAD

**Issue by RFuller25** [bjucps209/spring22-team1#11]
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "model.Coordinate.isNearThis(model.Coordinate)" because "this.location" is null
        at model.City.fireProjectile(City.java:162)
        at model.Game.update(Game.java:180)
        at model.Game.lambda$9(Game.java:521)
```

**Comment by RFuller25** [comment]
We used getLocation() instead of this.location
