### ISSUE TITLE
Null Pointer - Index out of range 

### ISSUE THREAD

**Issue by RFuller25** [bjucps209/spring22-team1#15]
```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at model.City.lambda$1(City.java:159)
```

**Comment by RFuller25** [comment]
Put an if statement in the thread that checks the length of the list.
